### ISSUE TITLE
A couple of issues with reported results "getSimulationMultiArmMeans" when using sample size re-assessment

### ISSUE THREAD

**Issue by TomParke** [rpact-com/rpact#14]
Running the following
designIN <- getDesignInverseNormal(kMax = 3, alpha = 0.025, typeOfDesign = "asOF", typeBetaSpending = "none")
simBonfSSREMAMS <- getSimulationMultiArmMeans(
  design = designIN,
  activeArms = 4,
  muMaxVector = seq(0,1,0.5),
  stDev = 1.5,
  plannedSubjects = c(30, 60, 90),
  intersectionTest = "Bonferroni",
  typeOfShape = "linear",
  typeOfSelection = "all",
  successCriterion = "all",
  minNumberOfSubjectsPerStage = c(22, 22, 22),
  maxNumberOfSubjectsPerStage = c(190, 190, 190),
  conditionalPower = 0.8,
  thetaH1 = 1,
  stDecH1 = 1.5,
  allocationRatioPlanned = 1.5,
  maxNumberOfIterations = maxNumberOfIterations,
  seed = 1234
)

I see two odd things in the  output, firstly the exit probabilities for futility are non zero but there is explicitly no futility stopping bound:
Exit probability for futility, mu_max = 0   0.5090 0.2666 
Exit probability for futility, mu_max = 0.5 0.1914 0.0817 
Exit probability for futility, mu_max = 1   0.0246 0.0258 

secondly the reported stage sizes are the same for every experimental arm (after sample size re-assessment) even though they are not simulated with the same treatment effect (using "linear"):

Stagewise number of subjects, mu_max = 0.5         
  Treatment arm 1                             30.0   75.3   38.7 
  Treatment arm 2                             30.0   75.3   38.7 
  Treatment arm 3                             30.0   75.3   38.7 
  Treatment arm 4                             30.0   75.3   38.7 
  Control arm                                 20.0   50.2   25.8 

Obviously I may have an input incorrect or be misinterpreting the results ... but I've double checked and don't see anything wrong or that explains either of these things in the output.

**Comment by fpahlke** [comment]
Hi Tom,

Thank you for the issue report. 
I was able to reproduce the issues/questions.
In the print output the "Exit probability for futility" is hidden, in the summary not. That has to be changed.
I will discuss this and also the "Stagewise number of subjects" with Gernot and respond soon.

Best,
Friedrich

**Comment by gwassmer** [comment]
Hi Tom,
Nice to hear from you!
Concerning yout first question:
There are "implicit" futility stops because you are using the Bonferroni adjustment: it might happen that the adjusted p-value is equal to one and therefore using the inverse normal method no rejection is possible anymore.
Your second question: 
I assume you are reporting one simulation case. Here, indeed, because no treatment arm selection is perfromed, the sample sizes are set equal for all active arms (calculated with the "worst case arm", i.e., the arm with smallest response)

Hope this helps 
Best regards
Gernot

**Comment by TomParke** [comment]
Hi Will, Gernot,

Many thanks for the explanations. 
1) Makes the Bonferroni even more unattractive if you have a lot of arms!
2) That’s an interesting limitation of the inverse combination that I wasn’t aware of.
3) Raises some interesting questions about sample size re-assessment with multiple arms. It suggests its only worth doing with some kind of filtering/selection. Having the next stage size driven by the weakest arm otherwise seems very undesirable. Of course doing unequal ssre for different groups changes allocation ratios to control for different arms which has other issues!

Many Thanks,
Tom
