### ISSUE TITLE
Automatic boundary calculation

### ISSUE THREAD

**Issue by gwassmer** [rpact-com/rpact#46]
For this case, no error message should be displayed (the number of stages for the dummy design can be arbitrary)

dummyDesign <- getDesignGroupSequential(kMax = 4, 
                                        alpha = 0.025,
                                        sided = 1,
                                        typeOfDesign = "asOF")
dataSurvival <- getDataset(cumulativeEvents = c(41, 86),
                           cumulativeLogRanks = c(-1.865, -2.510))
getAnalysisResults(design = dummyDesign,
                   dataInput = dataSurvival,
                   directionUpper = FALSE,
                   maxInformation = 120) |> summary()

**Comment by fpahlke** [comment]
Fixed in pull request [48](https://github.com/rpact-com/rpact/pull/48).
