### ISSUE TITLE
error in plot for getSimulationSurvival

### ISSUE THREAD

**Issue by liuxiangyu127** [rpact-com/rpact#60]
designIN <- getDesignInverseNormal(informationRates = c(0.4, 0.7, 1))

resultsWithSSR1 <- getSimulationSurvival(
  design = designIN,
  hazardRatio = seq(1, 1.6, 0.1),
  pi2 = 0.3, conditionalPower = 0.8, thetaH1 = 1.3,
  plannedEvents = c(58, 102, 146),
  minNumberOfEventsPerStage = c(NA, 44, 44),
  maxNumberOfEventsPerStage = 4 * c(NA, 44, 44),
  maxNumberOfSubjects = 800, maxNumberOfIterations = 50
)
plot(resultsWithSSR1)

I used the examples from the help document, but the plot() yielded the following errors:
Error in `mapply()`:
! The `legend.position.inside` theme element is not defined in the element hierarchy.
Run `rlang::last_trace()` to see where the error occurred.

**Comment by gwassmer** [comment]
Please update ggplot2, then it works
