### ISSUE TITLE
[Request] Minor wording change in rpact_survival_examples vignette

### ISSUE THREAD

**Issue by wolbersm** [rpact-com/rpact#62]
Could you please change "co-primary" by "two primary" in the this vignette, specifically:

- "Example: PFS and OS as co-primary endpoints, OS interim aligned with PFS final analysis" --> "Example: Both PFS and OS as primary endpoints, OS interim aligned with PFS final analysis"
- "Overall Type I error 5% (two-sided), 1:1 randomized with PFS and OS as co-primary endpoints." --> "Overall Type I error 5% (two-sided), 1:1 randomized with PFS and OS both as primary endpoints."

The reason for this request is that the [FDA guideline on multiple testing](https://www.fda.gov/media/162416/download) and also the EMA use the term "co-primary" only for the setting where significance on all endpoints is required for "success" (and, consequently, no multiple testing adjustment is needed) whereas the setting in the vignette is that if only PFS or OS are significant, this is already considered a "success" (and, consequently, a multiple testing adjustment is needed such as an alpha-split in the example). 

It would be great if the vignette could align with this terminology. Thanks a lot!

PS:  Most likely, I introduced this "bug" myself in the initial draft of the vignette. Sorry!

**Comment by fpahlke** [comment]
Thank you, Marcel, for the request. The updated version of the vignette is now online: [rpact_survival_examples](https://www.rpact.org/vignettes/planning/rpact_survival_examples/)
