### ISSUE TITLE
Specification of unequally spaced dose levels for multi-arm designs

### ISSUE THREAD

**Issue by gwassmer** [rpact-com/rpact#63]
For typeOfShape = "linear" and typeOfShape = "sigmoidEmax" there will be the possibility to specify unequally spaced dose levels.

**Comment by fpahlke** [comment]
## Original request from an rpact user

We were trying to use the function ‘getSimulationMultiArmMeans’ for simulating multi-arm multi-stage designs with a continuous endpoint. However, after reading the vignette and manual, we still have a couple questions and would like to consult with you.

Our question is about whether this function supports unequally-spaced dose levels. Suppose we have four active treatment arms to be compared with control, whose dose levels are 1, 2.5, 10, 20 mg, respectively. And we assume the dose-response relationship to be sigmoid Emax. Our initial investigation shows that the function only requires the following input arguments to determine the dose-response curve and the effect sizes of each active treatment arm, and there is no input argument for dose levels.

1. activeArms: number of active treatment arms
2. typeOfShape: shape of the dose-response relationship over the treatment groups
3. gED50: ED50 of the sigmoid Emax model
4. slope: slope of the sigmoid Emax model
5. muMaxVector: effect sizes for the treatment group with highest response.

From the output, it seems that the function automatically assumes that the active treatment arms are in equally-spaced doses, i.e., 0 for control and 1, 2, 3, 4 for the four active treatment arms.

The only workaround we identified is to specify the typeOfShape = "userDefined" and then use ‘effectMatrix’ to specify effect sizes that correspond to each treatment arm. This maybe straightforward for linear dose-response relationship but would require some extra work for sigmoid Emax. So we wanted to double check with you if this is the only way we could do, or if there is any other function we could use for this purpose.

## Answer by RPACT

You are right, with typeOfShape = "sigmoidEmax", rpact only supports equally spaced dose levels. If these are spaced unequally, you have to define effectMatrix manually, i.e., specifying effectMatrix with typeOfShape = "userDefined". So slope and ED50 need to defined "outside" rpact when specifying effectMatrix using the functional form of sigmoidEmax which is provided in Sect. 7.2.9.3 of the validation documentation.

## Feature request

Thanks a lot for your reply and the information in the validation documentation. It’s very helpful.

I wonder if rpact would consider adding this feature, i.e., allowing users to specify unequally-spaced dose levels, to the package in the future. This would be extremely helpful, especially for those who have difficulty calculating effect sizes from a particular sigmoid Emax model.
