### ISSUE TITLE
Improve documentation on `getSampleSizeSurvival()`

### ISSUE THREAD

**Issue by DanChaltiel** [rpact-com/rpact#8]
Hi,

First, thank you for this incredibly useful package.

I am trying to set up a GS design using `rpact`. The code looks like this:

```r
design <- getDesignGroupSequential(kMax=3, typeOfDesign="asOF", 
                                   alpha=0.025, beta=0.2, sided=1)
designPlan <- getSampleSizeSurvival(design, pi1=1-0.66, pi2=1-0.54, eventTime=3,
                                    accrualTime=3, followUpTime=2)
``` 

I am trying to validate this design against the software we are using, East. 
Please find attached the output of the same design: [east.zip](https://github.com/rpact-com/rpact/files/12652219/east.zip)

I can find the same results, which is very satisfying 😁

However, the output is sometimes a bit confusing and I couldn't find any extensive documentation

  -  `Expected study duration = 4.40`, although `Analysis time = 2.43, 3.61, 5.00`. No interim analysis is planned at t=4.4, how could the study end at that moment?
  - `Expected number of events under [H0, H0/H1, H1]`: what are these referring to? They are all different from `Number of events per stage`.
  - Moreover, the expected number of events (and therefore the analysis time), should be different under H0 and H1, as the survival hypothesis would be different. This is the case in the East example.
  - `Expected number of subjects under H1 = 461.4`: How is that different from `Number of subjects [1,2,3]`? Aren't the latter under H1 too? Maybe the considered hypothesis would be worth adding to the output here.

Of note, it would be very nice if `designPlan` could hold a reference to `design` internally, as it contains useful information to interpret it later (like the type of design for instance).
I'd be glad to make a PR if needed.

**Comment by fpahlke** [comment]
Hi Dan,

Thank you for your comments and questions. I will discuss them with my colleague Gernot and respond to you later.

The `designPlan` already holds an internal reference to `design`: Use `designPlan$.design`

Best,
Friedrich

**Comment by gwassmer** [comment]
Thank you for your interest in rpact. 
I try to answer your question as follows:
An expectation is a theoretical quantity that needs not necessarily be "observable".
If you play dice, for example, the expected outcome is 3.5 = (1 + 2 + 3 + 4 + 5+ 6) / 6.
And there is no outcome "3.5"!
The same is true for the expected study duraction, the expected number of events, and the expected number of subjects.
Does this help?
Kind regards,
Gernot Wassmer
